config/routes.rb
Rails.application.routes.draw do
  root to: "public/homes#top"
  get "about" =>"public/homes#about"

  devise_for :members,skip: [:passwords,], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  scope module: :public do
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :update, :destroy, :create] do
      collection do
        delete :destroy_all
      end
    end
    resources :orders, only: [:index, :show, :new, :create] do
      collection do
        get :confirm
        post :confirm
        get :order_fix
      end
    end
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    resources :members, only: [:show, :edit, :update] do
      collection do
        get :unsubscribe
        patch :withdraw
      end
    end
  end

  namespace :admin do
    root to: "homes#top"
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :orders, only: [:show, :update] do
      resources :item_orders, only: [:update]
    end
    resources :genres, only: [:index, :create, :edit, :update]
    resources :members, only: [:index, :show, :edit, :update]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :member,optional: true

  validates :post_number, presence: true
  validates :address, presence: true
  validates :name, presence: true

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :member

  validates :count, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy
  belongs_to :genre

  attachment :image

  enum sales_status: { 販売中: 0, 販売中止: 1 }

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
end

app/models/item_order.rb
class ItemOrder < ApplicationRecord
 belongs_to :item
 belongs_to :order

 enum making_status: { impossible: 0, wait: 1, production: 2,completion: 3 }
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

  validates :is_deleted, inclusion: { in: [true, false] }
  validates :last_name,:first_name, presence: true,
    length: {in: 1..20 }
  validates :last_name_kana,:first_name_kana, format: {with: /\A[ァ-ヶー－]+\z/ , message: "全角カタカナで入力してください。"},
    length: {in: 1..20 }
  validates :address, presence: true
  validates :post_number, format: {with: /\A\d{7}\z/ , message: "ハイフンなしの７文字で入力してください。"}
  validates :phone_number, format: {with: /\A\d{10,11}\z/ , message: "ハイフンなし10～11文字で入力してください。"}

  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/models/order.rb
class Order < ApplicationRecord
 has_many :item_orders, dependent: :destroy
 belongs_to :member

 enum payment_methods: { credit_card: 0, transfer: 1 }
 enum order_status: { payment_waiting: 0,payment_confirmation: 1,in_production: 2,preparing_delivery: 3,delivered: 4 }

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genres = Genre.all
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end



  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!,except: [:sign_in]
  def top
    @orders = Order.all.page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render "new"
    end
  end

  def index
    @items = Item.page(params[:page]).per(5).reverse_order
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      render "edit"
    end
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :price, :image, :sales_status)
  end

end

app/controllers/admin/members_controller.rb
class Admin::MembersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @members = Member.order(created_at: :asc).page(params[:page]).per(10)
  end

  def show
    @member = Member.find(params[:id])
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
    if @member.update(member_params)
    redirect_to admin_member_path(@member), notice: "変更を保存しました"
    else
      render :edit
    end
  end

  private

  def member_params
    params.require(:member).permit(:last_name,:first_name,:last_name_kana,:first_name_kana,:post_number,:address,:phone_number,:email,:is_deleted)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @orders = Order.all.page(params[:page]).per(10)
  end

  def show
    @order = Order.find(params[:id])
    @item_orders = @order.item_orders
    @postage = 800
    @total_payment = 0
    @item_orders.each do |item_orders|
      @total_payment += ((item_orders.item.price*item_orders.count)*1.1).floor
    end
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    if @order.order_status == "payment_confirmation"
      @order.item_orders.each do |item_order|
      item_order.making_status = "wait"
      item_order.save
      end
    end
    redirect_to request.referer
  end

  private

  def order_params
    params.require(:order).permit(:order_status)
  end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/item_orders_helper.rb
module Admin::ItemOrdersHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row p-4 mb-2">
    <h4 class="bg-light text-black">ジャンル編集</h4>
  </div>

  <br>

  <div class="row">
 　  <%= form_with model: @genre, url:admin_genre_path do |f| %>
    　<div class="form-group row">
    　　  <div><%= f.label :ジャンル名 %></div>
  　　　　  <div><%= f.text_field :name %></div>
  　　　　  <div><%= f.submit "変更を保存", class: "btn btn-success" %></div>
  　　  </div>
  　  <% end %>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row p-4">
    <div class="bg-light"><h4>ジャンル一覧・追加</h4></div>
  </div>
  <div class="row"></div>
      <%= form_with model: @genre, url:admin_genres_path do |f| %>
        <div class="p-4 form-group">
          <table class="col-5">
            <td><%= f.label :ジャンル名 %></td>
            <td><%= f.text_field :name %></td>
            <td><%= f.submit "新規登録", class: "btn btn-success"%></td>
          </table>
        </div>
      <% end %>
  </div>

  <div class="row offset-1 col-5">
    <table class="table">
      <thead class="table-active">
        <tr>
          <th>ジャンル</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @genres.each do |genre| %>
          <tr>
            <td>
              <%= genre.name %>
            </td>
            <td>
              <%= link_to "編集する", edit_admin_genre_path(genre), class: "btn btn-success" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/items/edit.html.erb
<div class="contents-title text-center p-4">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 px-2 mx-sm-auto">
      <div class="mb-4 bg-light">
        <h3><strong>商品編集</strong></h3>
      </div>
      <div class="form-body p-10">
      <!--エラーメッセージここから<<<-->
      <%= render 'layouts/errors', obj: @item %>
      <!--ここまで>>>-->
      <%= form_with(model:[@item], url:admin_item_path, local:true) do |f| %>
      <div class="row pb-3 ">
          <%= f.label :image, class: "col-sm-2 control-label font-weight-bold" %>
          <div class="col-sm-10">
            <div class="custom-file">
              <%= f.attachment_field :image, class: "custom-file-input w-100" %>
              <label class="custom-file-label text-left text-muted" for="inputFile" data-browse="参照" >画像を選択してください</label>
          </div>
        </div>
      </div>
      <div class="row pb-3">
        <%= f.label :name, class: "col-sm-2 control-label font-weight-bold" %>
          <div class="col-sm-10">
            <%= f.text_field :name, placeholder: "商品名", class: "form-control" %>
          </div>
      </div>
      <div class="row pb-3">
        <%= f.label :introduction, class: "col-sm-2 control-label font-weight-bold" %>
          <div class="col-sm-10">
            <%= f.text_field :introduction, placeholder: "ここに説明文を記述します", class: "form-control" %>
          </div>
      </div>
      <div class="row pb-3">
        <%= f.label :genre_id, class: "col-sm-2 control-label font-weight-bold" %>
          <div class="col-sm-10">
            <%= f.collection_select :genre_id, Genre.all, :id, :name,{prompt: "選択してください"},class: "form-control text-muted" %>
          </div>
      </div>
      <div class="row pb-3">
        <%= f.label :price, class: "col-sm-2 control-label font-weight-bold" %>
          <div class="col-sm-10">
            <%= f.number_field :price, placeholder: "1000", class: "form-control" %>
          </div>
      </div>
      <div class="row">
          <%= f.label :sales_status,class: "col-form-label font-weight-bold" %>
          <div class="pl-5">
            <%= f.radio_button :sales_status, :"販売中" %>
            <%= f.label :sales_status, "販売中", checked: true %>
            <%= f.radio_button :sales_status, :"販売中止" %>
            <%= f.label :sales_status, "販売中止" %>
          </div>
      </div>
      <%= f.submit '変更を保存', class: "btn btn-primary" %>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="contents-title text-center p-4">
  <div class="row justify-content-center">
    <div class="col-md-3 text-left mb-4 mr-5 text-center bg-light">
      <h3><strong>商品一覧</strong></h3>
    </div>
    <div class="col-md-4 text-right text-secondary ">
       <%= link_to "ジャンル登録", admin_genres_path, class: "mr-5 btn btn-info" %>
      <%= link_to "商品追加", new_admin_item_path, class: "mr-5 btn btn-success" %>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-md-8 text-left">
      <table class="table table-hover" >
        <tr class="table-active">
            <th class="col-1">商品名ID</th>
            <th class="col-2">商品名</th>
            <th class="col-1">税抜価格</th>
            <th class="col-2">ジャンル</th>
            <th class="col-2">ステータス</th>
          </tr>
          <tbody>
            <% @items.each do |item| %>
              <tr>
                <td class="col-1 align-middle">
                  <%= item.id %>
                </td>
                <td class="col-2 align-middle">
                  <%= link_to admin_item_path(item.id), class: "text-secondary" do %>
                    <%= item.name %>
                  <% end %>
                </td>
                <td class="col-1 align-middle">
                  <%= item.price %>
                </td>
                <td class="col-2 align-middle">
                  <%= item.genre.name %>
                  </td>
                <td class="col-2 align-middle h6 font-weight-bold">
                  <% case item.sales_status when "販売中" %>
                  <span style="color: green;"><%= item.sales_status %></span>
                  <% when "販売中止" %>
                  <span style="color: dimgray;"><%= item.sales_status %></span>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>
  </div>
  <div class="row justify-content-center">
    <div class="col-8">
      <%= paginate @items %>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="contents-title text-center p-4">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 px-2 mx-sm-auto">
      <div class="mb-4 bg-light">
        <h3><strong>新規投稿フォーム</strong></h3>
      </div>

      <div class="form-body p-10">
      <!--エラーメッセージここから<<<-->
      <%= render 'layouts/errors', obj: @item %>
      <!--ここまで>>>-->

      <%= form_with(model:[@item], url:admin_items_path, local:true) do |f| %>
      <div class="row pb-3 ">
          <%= f.label :image, class: "col-sm-2 control-label font-weight-bold" %>
          <div class="col-sm-10">
            <div class="custom-file">
              <%= f.attachment_field :image, class: "custom-file-input w-100" %>
              <label class="custom-file-label text-left text-muted" for="customFile" data-browse="参照" >画像を選択してください</label>
          </div>
        </div>
      </div>
      <div class="row pb-3">
        <%= f.label :name, class: "col-sm-2 control-label font-weight-bold" %>
          <div class="col-sm-10">
            <%= f.text_field :name, placeholder: "商品名", class: "form-control" %>
          </div>
      </div>
      <div class="row pb-3">
        <%= f.label :introduction, class: "col-sm-2 control-label font-weight-bold" %>
          <div class="col-sm-10">
            <%= f.text_field :introduction, placeholder: "ここに説明文を記述します", class: "form-control" %>
          </div>
      </div>
      <div class="row pb-3">
        <%= f.label :genre_id, class: "col-sm-2 control-label font-weight-bold" %>
          <div class="col-sm-10">
            <%= f.collection_select :genre_id, Genre.all, :id, :name,{prompt: "選択してください"},class: "form-control text-muted" %>
          </div>
      </div>
      <div class="row pb-3">
        <%= f.label :price, class: "col-sm-2 control-label font-weight-bold" %>
          <div class="col-sm-10">
            <%= f.number_field :price, placeholder: "1000", class: "form-control" %>
          </div>
      </div>
      <div class="row">
          <%= f.label :sales_status,class: "col-form-label font-weight-bold" %>
          <div class="pl-5">
            <%= f.radio_button :sales_status, :"販売中" %>
            <%= f.label :sales_status, "販売中", checked: true %>
            <%= f.radio_button :sales_status, :"販売中止" %>
            <%= f.label :sales_status, "販売中止" %>
          </div>
      </div>
      <%= f.submit '新規登録', class: "btn btn-primary" %>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="contents-title text-center p-4">
  <div class="row align-items-center justify-content-sm-center">
    <div class="col-xl-5 col-md-12">
      <div class="row">
        <div class="col-xl-4 "></div>
        <div class="col-xl-8 col-lg-8 text-md-center">
        </div>
      </div>
      <div class="text-md-center " >

        <%= attachment_image_tag @item, :image, size: "500x400", fallback: "no_image.jpg" %>
      </div>
    </div>
    <div class="col-xl-7 col-lg-8 ">
      <div class="text-left justify-content-md-end">
        <table class="table table-borderless d-flex w-75 ">
          <tr>
            <td class="font-weight-bold col-3">商品名</td>
            <td><%= @item.name %></td>
          </tr>
          <tr>
            <td class="font-weight-bold col-3 ">商品説明</td>
            <td><%= @item.introduction %></td>
          </tr>
          <tr>
            <td class="font-weight-bold col-3">ジャンル</td>
            <td><%= @item.genre.name %></td>
          </tr>
          <tr>
            <td class="font-weight-bold col-3">
              <p class="p-0"> 税込価格<br>(税抜価格)</p>
            </td>
            <td>
              <p class="pt-3"><%= ((@item.price.to_i * 1.1).round).to_s(:delimited) %>(<%= (@item.price).to_s(:delimited) %>)円</p>
            </td>
          </tr>
          <tr>
            <td class="font-weight-bold mr-5">販売ステータス</td>
            <td class="h6 font-weight-bold">
              <% case @item.sales_status when "販売中" %>
              <span style="color: green;"><%= @item.sales_status %></span>
              <% when "販売中止" %>
              <span style="color: dimgray;"><%= @item.sales_status %></span>
              <% end %>
            </td>
          </tr>
        </table>
      </div>
      <div class="text-left w-30">
        <%= link_to "編集する", edit_admin_item_path(@item), class: "btn btn-primary p-2" %>
        <%= link_to "新規商品登録", new_admin_item_path, class: "btn btn-success p-2" %>
        <%= link_to "商品一覧", admin_items_path, class: "btn btn-success p-2" %>
      </div>
    </div>
  </div>
</div>

app/views/admin/members/edit.html.erb
<main>
  <div class="container pb-1">
   <%= render 'layouts/errors', obj:@member %>
    <div class="row pt-4 mb-4">
      <h4>
        <%= @member.last_name %><%= @member.first_name %>さんの会員情報編集
      </h4>
    </div>

      <%= form_with(model:[:admin,@member],local:true) do |f| %>

      <div class="form-group row justify-content-start mt-2 mb-3">
         <div class="col-sm-3 align-self-center">会員ID</div>
            <%= @member.id %>
      </div>

      <div class="form-group row justify-content-start mt-2 mb-3">
         <div class="col-sm-3 align-self-center">氏名</div>
            <%= f.text_field :last_name,autofocus: true,class:"mr-5" %>
            <%= f.text_field :first_name,autofocus: true %>
      </div>

      <div class="form-group row justify-content-start mt-2 mb-3">
         <div class="col-sm-3 align-self-center">フリガナ</div>
            <%= f.text_field :last_name_kana,autofocus: true,class:"mr-5" %>
            <%= f.text_field :first_name_kana,autofocus: true %>
      </div>

      <div class="form-group row justify-content-start mt-2 mb-3">
         <div class="col-sm-3 align-self-center">郵便番号</div>
            <%= f.text_field :post_number,autofocus: true  %>
      </div>

      <div class="form-group row justify-content-start mt-2 mb-3">
         <div class="col-sm-3 align-self-center">住所</div>
            <%= f.text_field :address,size: "80x2",autofocus: true %>
      </div>

      <div class="form-group row justify-content-start mt-2 mb-3">
         <div class="col-sm-3 align-self-center">電話番号</div>
            <%= f.text_field :phone_number,autofocus: true %>
      </div>

      <div class="form-group row justify-content-start mt-2 mb-3">
         <div class="col-sm-3 align-self-center">メールアドレス</div>
            <%= f.text_field :email,autofocus: true %>
      </div>

      <div class="form-group row justify-content-start mt-2 mb-3">
         <div class="col-sm-3 align-self-center">会員ステータス</div>
            <label><%= f.radio_button :is_deleted, :false %> 有効</label>
            <label><%= f.radio_button :is_deleted, :true %> 退会</label>
      </div>

      <div class="form-group row justify-content-start mt-2 pb-4">
        <div class="col-sm-3  ofset-sm-1"></div>
          <%= f.submit "変更を保存", class: "btn btn-success col-sm-2" %>
      </div>
      <% end %>
  </div>
</main>

app/views/admin/members/index.html.erb
<main>
  <div class="container">
    <div class="row pt-4 mb-2">
      <h4 class="offset-md-1">会員一覧</h4>
     </div>

     <div class="row">
      <table class="table col-md-9 mx-auto bg-light">
        <tr class="background-color">
          <th>会員ID</th>
          <th>氏名</th>
          <th>メールアドレス</th>
          <th>ステータス</th>
        </tr>

        <tbody>
          <% @members.each do |member| %>
          <tr>
            <td><%= member.id %></td>
            <td>
              <%= link_to admin_member_path(member) do %>
              <%= member.last_name%><%= member.first_name %>
              <% end %>
              </td>
            <td><%= member.email %></td>
            <% if member.is_deleted == false %>
              <td class="font-weight-bold text-success">
                <%= member.is_deleted ? '退会':'有効' %>
              </td>
            <% else %>
              <td class="font-weight-bold text-secondary">
                <%= member.is_deleted ? '退会':'有効' %>
              </td>
            <% end %>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>

    <div class="row">
      <div class="col-md-3 mx-auto">
        <%= paginate @members %>
      </div>
    </div>
 </div>
</main>

app/views/admin/members/show.html.erb
<main>
  <div class="container px-sm-0">
    <div class="row pt-4 mb-2">
       <h4>
         <%= @member.last_name %><%= @member.first_name %>さんの会員詳細
        </h4>
     </div>
    <div class="row">
      <div class="col-md-9">
          <table class="table table-borderless">
            <tbody>
              <tr>
                <td>会員ID</td><td><%= @member.id %></td>
              </tr>
              <tr>
                <td>氏名</td><td><%= @member.last_name %><%= @member.first_name %></td>
              </tr>
              <tr>
                <td>フリガナ</td><td><%= @member.last_name_kana %><%= @member.first_name_kana %></td>
              </tr>
              <tr>
                <td>郵便番号</td><td><%= @member.post_number %></td>
              </tr>
              <tr>
                <td>住所</td><td><%= @member.address %></td>
              </tr>
               <tr>
                <td>電話番号</td><td><%= @member.phone_number %></td>
              </tr>
               <tr>
                <td>メールアドレス</td><td><%= @member.email %></td>
              </tr>
               <tr>
                <td>会員ステータス</td>
                  <% if @member.is_deleted == false %>
                    <td class="font-weight-bold text-success">
                    <%= @member.is_deleted ? '退会':'有効' %>
                    </td>
                  <% else %>
                    <td class="font-weight-bold text-secondary">
                    <%= @member.is_deleted ? '退会':'有効' %>
                    </td>
                  <% end %>
              </tr>
            </tbody>
          </table>
     </div>
    </div>

  <div class="row pb-4">
    <div class="col-md-2 offset-2">
      <%= link_to '編集する',edit_admin_member_path(@member), class: "btn btn-success text-light" %>
    </div>
    <div class="col-md-8">
      <%= link_to '注文履歴一覧を見る',admin_root_path, class: 'btn btn-primary text-light' %>
    </div>

  </div>

 </div>
</main>

app/views/admin/orders/_index.html.erb
<div class="container">
  <div class="row p-5">
    <h4 class="bg-light">注文履歴一覧</h4>
  </div>

  <div class="row">
    <table class="table col-10 mx-auto">
      <thead class="bg-light">
        <th class="col-3">購入日時</th>
        <th class="col-2">購入者</th>
        <th class="col-3">注文個数</th>
        <th class="col-3">注文ステータス</th>
      </thead>

      <tbody>
        <% orders.reverse_each do |order| %>
          <tr>
            <td><%= link_to order.created_at.strftime("%Y/%m/%d %H:%M:%S"), admin_order_path(order) %></td>
            <td><%= order.member.last_name %> <%= order.member.first_name %></td>
            <td><%= order.item_orders.sum(:count) %></td>
            <td><%= order.order_status_i18n %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<%= paginate orders %>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row p-5">
    <h4 class="bg-light">注文履歴詳細</h4>
  </div>
        <%= form_with model:@order, url:admin_order_path(@order), method: :patch  do |f| %>
  <div class="row">
    <div class="offset-md-1 col-10">
      <table class="order_detail">
        <tr>
          <th class="p-1">購入者</th>
          <td>
            <b>
            <%= link_to admin_member_path(@order.member_id) do %>
              <%= @order.member.last_name %><%= @order.member.first_name %>
            <% end %>
            </b>
          </td>
          <td></td>
        </tr>
        <tr>
          <th class="p-1">注文日</th>
          <td><%= @order.created_at.strftime("%Y/%m/%d") %></td>
          <td></td>
        </tr>
        <tr>
          <th class="p-1">配送先</th>
          <td>
            <p>〒<%= @order.post_number %> <%= @order.address %>
                   <%= @order.name %>
            </p>
          </td>
          <td></td>
        </tr>
        <tr>
          <th class="p-1">支払い方法</th>
          <td><%= @order.payment_methods_i18n %></td>
        </tr>

        <tr>
          <th class="p-1 col-5">注文ステータス</th>
          <td>
              <%= f.select :order_status, Order.order_statuses_i18n.invert %>
          </td>
          <td>
              <%= f.submit "更新", class: "btn btn-success ml-3" %>
          </td>
        <% end %>
        </tr>
      </table>
    </div>
  </div>

  <div class="row">
    <div class="col-9 p-5">
      <table class="table mx-auto">
        <thead class="table-light">
          <tr>
            <th class="col-2">商品名</th>
            <th class="col-2">単価(税込)</th>
            <th class="col-1">数量</th>
            <th class="col-1">小計</th>
            <th class="col-3">製作ステータス</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @order.item_orders.each do |item_orders| %>
          <tr>
            <td><%= item_orders.item.name %></td>
            <td><%= (item_orders.item.price*1.1).to_i %></td>
            <td><%= item_orders.count %></td>
            <%#単価×数量の合計値を表示する%>
            <td>
                <% subtotal = ((item_orders.item.price*item_orders.count)*1.1).to_i %>
                <%= subtotal %>
            </td>
            <%= form_with model:[@order,item_orders], url:admin_order_item_order_path(@order,item_orders),  local: true do |f| %>
            <td><%= f.select :making_status, ItemOrder.making_statuses_i18n.invert %> </td>
            <td><%= f.submit "更新", class: "btn btn-success ml-3" %></td>
            <td></td>
            <% end %>
          <% end %>
          </tr>
        </tbody>
      </table>
    </div>

    <div class="col-3 p-5">
      <table class= "table table-bordered bg-light">
        <p class="text-right">
        <tr>
          <td>商品合計</td>
          <td><%= @total_payment %>円</td>
        </tr>
        <tr>
          <td>送料</td>
          <td><%= @postage %>円</td>
        </tr>
        <tr>
          <td>請求額合計</td>
          <td><%= @total_payment + @postage %>円</td>
        </tr>
        </p>
      </table>
    </div>
  </div>
</div>