config/routes.rb
Rails.application.routes.draw do
  root to: "public/homes#top"
  get "about" =>"public/homes#about"

  devise_for :members,skip: [:passwords,], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }
  scope module: :public do
    resources :items, only: [:index, :show]
    resources :cart_items, only: [:index, :update, :destroy, :create] do
      collection do
        delete :destroy_all
      end
    end
    resources :orders, only: [:index, :show, :new, :create] do
      collection do
        get :confirm
        post :confirm
        get :order_fix
      end
    end
    resources :addresses, only: [:index, :create, :edit, :update, :destroy]
    resources :members, only: [:show, :edit, :update] do
      collection do
        get :unsubscribe
        patch :withdraw
      end
    end
  end

  namespace :admin do
    root to: "homes#top"
  end

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :orders, only: [:show, :update] do
      resources :item_orders, only: [:update]
    end
    resources :genres, only: [:index, :create, :edit, :update]
    resources :members, only: [:index, :show, :edit, :update]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :member,optional: true

  validates :post_number, presence: true
  validates :address, presence: true
  validates :name, presence: true

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :member

  validates :count, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy
  belongs_to :genre

  attachment :image

  enum sales_status: { 販売中: 0, 販売中止: 1 }

  validates :name, presence: true
  validates :introduction, presence: true
  validates :price, presence: true
end

app/models/item_order.rb
class ItemOrder < ApplicationRecord
 belongs_to :item
 belongs_to :order

 enum making_status: { impossible: 0, wait: 1, production: 2,completion: 3 }
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

  validates :is_deleted, inclusion: { in: [true, false] }
  validates :last_name,:first_name, presence: true,
    length: {in: 1..20 }
  validates :last_name_kana,:first_name_kana, format: {with: /\A[ァ-ヶー－]+\z/ , message: "全角カタカナで入力してください。"},
    length: {in: 1..20 }
  validates :address, presence: true
  validates :post_number, format: {with: /\A\d{7}\z/ , message: "ハイフンなしの７文字で入力してください。"}
  validates :phone_number, format: {with: /\A\d{10,11}\z/ , message: "ハイフンなし10～11文字で入力してください。"}

  def active_for_authentication?
    super && (is_deleted == false)
  end
end

app/models/order.rb
class Order < ApplicationRecord
 has_many :item_orders, dependent: :destroy
 belongs_to :member

 enum payment_methods: { credit_card: 0, transfer: 1 }
 enum order_status: { payment_waiting: 0,payment_confirmation: 1,in_production: 2,preparing_delivery: 3,delivered: 4 }

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genres = Genre.all
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end



  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!,except: [:sign_in]
  def top
    @orders = Order.all.page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      render "new"
    end
  end

  def index
    @items = Item.page(params[:page]).per(5).reverse_order
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      render "edit"
    end
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :price, :image, :sales_status)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/item_orders_helper.rb
module Admin::ItemOrdersHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger" role="alert">
        <ul  class="mb-0">
        <% obj.errors.full_messages.each do |message| %>
          <dd><%= message %></dd>
        <% end %>
        </ul>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/cb9870c1ab.js" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="header-color container-fluid border border-5">
        <div class="row justify-content-between">
          <a class="col-auto mr-auto p-3 m-0" href="/"><%= image_tag('logo3.png', :size =>'110x80') %></a>
          <div class="col-md-lg-auto mr-3 align-self-center">
            <% if member_signed_in? && admin_signed_in? %>
             <button class= "btn btn-light mr-3 border border-secondary">
              <%= link_to "商品一覧", admin_items_path, class: "text-dark" %>
            </button>
            <button class= "btn btn-light mr-3 border border-secondary">
              <%= link_to "会員一覧", admin_members_path, class: "text-dark" %>
            </button>
            <button class= "btn btn-light mr-3 border border-secondary">
              <%= link_to "注文履歴一覧", admin_root_path, class: "text-dark" %>
            </button>
            <button class= "btn btn-light mr-3 border border-secondary">
              <%= link_to "ジャンル一覧", admin_genres_path, class: "text-dark" %>
            </button>
            <button class= "btn btn-light border border-secondary">
              <%= link_to "ログアウト", destroy_admin_session_path,method: :delete, class: "text-dark" %>
            </button>
            <% elsif member_signed_in? %>
            <button class= "btn btn-light mr-3 border border-secondary">
              <%= link_to "マイページ", member_path(current_member.id), class: "text-dark" %>
            </button>
            <button class= "btn btn-light mr-3 border border-secondary">
              <%= link_to "商品一覧", items_path, class: "text-dark" %>
            </button>
            <button class= "btn btn-light mr-3 border border-secondary">
              <%= link_to "カート", cart_items_path(current_member.id), class: "text-dark" %>
            </button>
            <button class= "btn btn-light border border-secondary">
              <%= link_to "ログアウト", destroy_member_session_path,method: :delete, class: "text-dark" %>
            </button>
            <% elsif admin_signed_in? %>
            <button class= "btn btn-light mr-3 border border-secondary">
              <%= link_to "商品一覧", admin_items_path, class: "text-dark" %>
            </button>
            <button class= "btn btn-light mr-3 border border-secondary">
              <%= link_to "会員一覧", admin_members_path, class: "text-dark" %>
            </button>
            <button class= "btn btn-light mr-3 border border-secondary">
              <%= link_to "注文履歴一覧", admin_root_path, class: "text-dark" %>
            </button>
            <button class= "btn btn-light mr-3 border border-secondary">
              <%= link_to "ジャンル一覧", admin_genres_path, class: "text-dark" %>
            </button>
            <button class= "btn btn-light border border-secondary">
              <%= link_to "ログアウト", destroy_admin_session_path,method: :delete, class: "text-dark" %>
            </button>
            <% else %>
            <button class= "btn btn-light mr-3 border border-secondary">
              <%= link_to "About", about_path, class: "text-dark" %>
            </button>
            <button class= "btn btn-light mr-3 border border-secondary">
              <%= link_to "商品一覧", items_path, class: "text-dark" %>
            </button>
            <button class= "btn btn-light mr-3 border border-secondary">
              <%= link_to "新規登録", new_member_registration_path, class: "text-dark" %>
            </button>
            <button class= "btn btn-light border border-secondary">
              <%= link_to "ログイン", new_member_session_path, class: "text-dark" %>
            </button>
            <% end %>
          </div>
        </div>
      </div>
    </header>
    <div class="back_image">
      <div id="notice"><%= flash[:notice] %></div>
      <%= yield %>
    </div>
    <footer>
      <div class="footer-color d-flex align-items-center justify-content-center border border-5">
          <h5 class=text-light>nagano_cake.Co., Ltd.</h5>
      </div>
    </footer>
  </body>
</html>